### ISSUE TITLE
Upgrade fail

### ISSUE THREAD

**Issue by doekia** [thirtybees/tbupdater#15]
While running the tdupdater, it raise the following error:
SQL 1.0.8 1064 in INSERT INTO `ps_configuration`(`name`, `value`, `date_add`, `date_upd`) SELECT 'TB_MAIL_SUBJECT_TEMPLATE', '[{shop_name}] {subject}', NOW(), NOW() WHERE ( SELECT COUNT(*) FROM `ps_configuration` WHERE `name` = 'TB_MAIL_SUBJECT_TEMPLATE' ) = 0: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE ( SELECT COUNT(*) FROM `ps_configuration` WHERE `name` = 'TB_M' at line 3

The SQL should be written:
INSERT INTO `ps_configuration`(`name`, `value`, `date_add`, `date_upd`)
SELECT 'TB_MAIL_SUBJECT_TEMPLATE', '[{shop_name}] {subject}', NOW(), NOW()
FROM (select 1) t 
WHERE ( SELECT COUNT(*) FROM `ps_configuration` WHERE `name` = 'TB_MAIL_SUBJECT_TEMPLATE' ) = 0

**Comment by Traumflug** [comment]
Thanks for the report. This module got replaced by module Core Updater, which does this task not with some fancy SQL, but by using class _Configuration_. This issue report was in mind when designing retrocompatibility in Core Updater, so it wasn't useless.

**Comment by dvershinin** [comment]
@Traumflug if it was replaced by something else - make it obvious in this repository's README. There are many articles online referring to tbupdater, and not core updater. People try to use tbupdater in vain. Me for instance :)
