### ISSUE TITLE
Small issues in the upgrade process.

### ISSUE THREAD

**Issue by SeeTwoDev** [thirtybees/tbupdater#2]
There's a random 'false' in the logs

And 3 inserts that failed :
[WARNING] SQL 1.0.1
1054 in INSERT INTO `tb_hook` (`hook_name`, `title`) VALUES ('actionRegisterAutoloader', 'actionRegisterAutoloader'): Unknown column 'hook_name' in 'field list'

[WARNING] SQL 1.0.1
1054 in INSERT INTO `tb_hook` (`hook_name`, `title`) VALUES ('actionRegisterErrorHandlers', 'actionRegisterErrorHandlers'): Unknown column 'hook_name' in 'field list'

[WARNING] SQL 1.0.1
1054 in INSERT INTO `tb_hook` (`hook_name`, `title`) VALUES ('actionRetrieveCurrencyRates', 'actionRetrieveCurrencyRates'): Unknown column 'hook_name' in 'field list'

**Comment by SeeTwoDev** [comment]
Tried adding them manually...successfully

But i'm having this issue while trying to see the module list : [PrestaShop] Fatal error in module file var/www/vdf.c2/public/modules/fixerio/fixerio.php:
Class FixerIo contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (CurrencyRateModuleCore::hookActionRetrieveCurrencyRates)

**Comment by firstred** [comment]
Hmmz, we had to break compatibility for Currency modules ( see the apologies in the phpdoc comments :stuck_out_tongue: ). I think this causes it. We should update the currency module files before upgrading the rest it seems.

**Comment by firstred** [comment]
`hook_name`. That is indeed incorrect. Should be `name`. Thanks!

**Comment by SeeTwoDev** [comment]
Think it will be fixed by tomorrow?

**Comment by firstred** [comment]
Both can be fixed by updating the packages that are downloaded from the API, so will be fixed in a minute.

**Comment by firstred** [comment]
Here's the repo: https://github.com/thirtybees/patchscripts

**Comment by SeeTwoDev** [comment]
You put `hook`, `title` instead of `name`, `title` btw

**Comment by firstred** [comment]
Yeah, that wouldn't fix it. Thanks!
