### ISSUE TITLE
Two placeholders, one argument

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/tbupdater#4]
Line 286 in `classes/AjaxProcessor.php` looks like this:
```php
$this->nextQuickInfo[] = sprintf($this->l('Files will be saved to %s and %s'), $this->getCoreFilePath());
```
Looks like there's either a placeholder too much or an argument missing.

See also https://forum.thirtybees.com/topic/340/upgrade-error-500

**Comment by firstred** [comment]
Changed! Thanks.
