### ISSUE TITLE
Error message with v1.2.0

### ISSUE THREAD

**Issue by yaniv14** [thirtybees/tbupdater#5]
Just update to v1.2.0 (with fresh tb 1.0.2 installation).
And I am getting error when entering the module.
Warning line 250 in file C:\wamp\www\tb102\modules\tbupdater\classes\SemVer\Expression.php
[2] preg_replace_callback(): Requires argument 2, 'Expression::xRangesToComparatorsCallback', to be a valid callback.

Also in the start your upgrade block I get error: Could not connect with the server

[screenshot](http://prntscr.com/fwqwnl)

**Comment by firstred** [comment]
That's a broken PHP PCRE extension

**Comment by firstred** [comment]
Nope, it's not. Some PHP versions don't know how to find classes with namespace. Still a PHP bug, but has to be solved from our side.

**Comment by firstred** [comment]
Solved with 1.2.1
