### ISSUE TITLE
 Invalid classname error when module installs

### ISSUE THREAD

**Issue by gingerling** [thirtybees/tbupdater#8]
I installed the module and I get "invalid classname" when I go to the modules tab. Tested with 1.2.2. and 1.2.3 of the plugin on tb 1.0.1 - this is in live site, it was fine on my test site a few weeks ago

**Comment by gofenice** [comment]
still the same issue with Version 1.2.5.

**Comment by gofenice** [comment]
@gingerling did you get solved this ?

**Comment by gofenice** [comment]
@firstred Do you have any suggestions on this issue? I have an PS1.6 that was already moved to TB 1.0 version and is running for more than 6 months, but can't upgrade to latest one due to this.

Thanks,

**Comment by Dh42** [comment]
Is the site already running thirty bees? If so delete the migration module and try.

**Comment by gofenice** [comment]
@Dh42 yes its already removed after migrating to TB, now we would like to upgrade to 1.0.3 but can't due to this error.

**Comment by gofenice** [comment]
finally i did manual upgrade and was successfully upgraded to 1.0.3

**Comment by Traumflug** [comment]
Updating thirty bees is now done with module Core Updater, which (hopefully) has no such issues. This module is going to get removed and is no longer subject for bug fixes.
